### ISSUE TITLE
Could not find artifact com.github.everit-org.json-schema:org.everit.json.schema:jar:1.11.0 in central (https://repo1.maven.org/maven2/)

### ISSUE THREAD

**Issue by hden** [luposlip/json-schema#1]

**Comment by luposlip** [comment]
Please supply sufficient code to reproduce.

I just wiped my `.m2` folder and created a sample app using `luposlip/json-schema` without any issues.

**Comment by hden** [comment]
deps.edn

```deps.edn
{:deps
 {luposlip/json-schema {:mvn/version "0.1.4"}}}
```

```
$ clj
Downloading: luposlip/json-schema/0.1.4/json-schema-0.1.4.pom from https://repo.clojars.org/
Error building classpath. Could not find artifact com.github.everit-org.json-schema:org.everit.json.schema:jar:1.11.1 in central (https://repo1.maven.org/maven2/)
```

It seems that `com.github.everit-org.json-schema/org.everit.json.schema` is no longer available on maven central.
https://search.maven.org/search?q=json-schema

**Comment by luposlip** [comment]
Ahh, not using `deps.edn` myself.
Can you try with this:

```clojure
{:deps
 {luposlip/json-schema {:mvn/version "0.1.4"}
  com.github.everit-org.json-schema/org.everit.json.schema {:git/url "https://github.com/everit-org/json-schema.git"
                        :sha "dd5e85b4c05c96c59a6b2a922d99e375b6ca116c"}}}
```

**Comment by hden** [comment]
```
$ clj
Cloning: https://github.com/everit-org/json-schema.git
Checking out: https://github.com/everit-org/json-schema.git at dd5e85b4c05c96c59a6b2a922d99e375b6ca116c
Downloading: luposlip/json-schema/0.1.4/json-schema-0.1.4.jar from https://repo.clojars.org/
Clojure 1.10.0


user=> (require '[json-schema.core :as schema])
Syntax error (ClassNotFoundException) compiling at (core.clj:1:1).
org.json.JSONObject
```

**Comment by luposlip** [comment]
As mentioned I don't use `deps.edn`. Until I get the time to look into it - can you use `lein` instead?

If not I advise you to find the dependencies yourself in the following file, and add them to your `deps.edn`:
https://github.com/everit-org/json-schema/blob/master/core/pom.xml

Let me know if you still have problems.

**Comment by hden** [comment]
Got it, thanks.

**Comment by luposlip** [comment]
Found out via Clojurians, that this is actually a bug in `tools.deps`:
https://dev.clojure.org/jira/browse/TDEPS-46

So for now, either do the manual copying of dependencies from the `pom.xml`, use `lein` instead or wait for the above Jira bug to be fixed :)

Closing this issue.
