### ISSUE TITLE
List not validated for type array

### ISSUE THREAD

**Issue by cburgmer** [luposlip/json-schema#7]
I have this schema:

```
{:$schema "http://json-schema.org/draft-04/schema"
 :type "array"}
```

Running the following will not validate if the input is a list:
```
(schema/validate my-schema my-input)
```

The work-around for now seems to be
```
(schema/validate my-schema (apply vector my-input))
```

**Comment by luposlip** [comment]
Sorry for the late reply. I'll take a look at it soon'ish!
